### ISSUE TITLE
iOS TypeError: undefined is not an object (evaluating 'sjcl.random')

### ISSUE THREAD

**Issue by hortonelectric** [tradle/react-native-crypto#10]
RN 0.39.2, node 7.x, using Remote Debugger, TypeError: undefined is not an object (evaluating 'sjcl.random') when running synchronous randomBytes call. When running it asynchronous, the output is null from the async call, though it does return the async call.

Found out that the Safari remote debugger does not work, due to the "error getting entropy from browser". But that it DOES work on the device. Maybe put this in the readme or output a more friendly error message to browser console.

**Comment by bjackson** [comment]
I get this error on Android.

**Comment by mvayngrib** [comment]
@bjackson have you installed and linked react-native-randombytes?

**Comment by GrzegorzZajac000** [comment]
Same error here (Android). react-native-randombytes installed and linked

**Comment by Cody-G-G** [comment]
Having the same issue on Android when trying to run, followed instructions, react-native-randombytes linked, etc.... any ideas?

**Comment by stwiname** [comment]
I have the same problem. It seems to go away if i enable remote js debugging

**Comment by mvayngrib** [comment]
are you guys using [rn-nodeify](https://github.com/mvayngrib/rn-nodeify) ?

**Comment by athanclark** [comment]
I am using rn-nodeify, on android, and including `import './shim.js';` at the top of my index.android.js, as per the README, as well. Oddly, it still seems that I get moderately random data, though.

**Comment by lcjnil** [comment]
Same issues here, in android platfrom.

**Comment by mvayngrib** [comment]
does this sample project work for you guys? https://github.com/mvayngrib/rnctest

**Comment by lcjnil** [comment]
@mvayngrib Thx for your reply, this project works fine (in android), but its react-native version is not latest.

**Comment by mvayngrib** [comment]
works fine for me on both ios and android with RN 0.42

https://github.com/mvayngrib/rnctest/tree/0.42

**Comment by athanclark** [comment]
@mvayngrib unfortunately this rnctest app isn't working for me on android. The log I got in `react-native log-android` was:

```
I/ReactNativeJS(18705): There was an error collecting entropy from the browser:
I/ReactNativeJS(18705): { [TypeError: undefined is not an object (evaluating 'sjcl.random')]
I/ReactNativeJS(18705):   line: 12548,
I/ReactNativeJS(18705):   column: 28,
I/ReactNativeJS(18705):   sourceURL: 'http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false' }
E/ReactNativeJS(18705): undefined is not an object (evaluating 'crypto.pbkdf2Sync.toString')
E/ReactNativeJS(18705): Module AppRegistry is not a registered callable module (calling runApplication)
```

I'm not exactly sure what android version I'm running, or the specific hardware, but I can try to find out. Thank you anyway for trying to tie this library together.

**Comment by mvayngrib** [comment]
@athanclark good catch, fixed in 2.0.2 (locked down pbkdf2 to 3.0.8)

**Comment by athanclark** [comment]
@mvayngrib hmm, it's still not working for me - I updated the package.json for rnctest to `react-native-crypto: ^2.0.2`, but I'm still getting the same error :\ I'm going to keep tinkering

**Comment by mvayngrib** [comment]
@athanclark did you make sure the pbkdf2 you have in node_modules is version 3.0.8? `npm install` and `yarn` f up sometimes too

**Comment by mvayngrib** [comment]
and don't forget to re-run: `rn-nodeify --hack` after you install anything

**Comment by athanclark** [comment]
Wow holy Toledo you are right! It's working like a charm now. Thank you!!

**Comment by mvayngrib** [comment]
@athanclark awesome, have fun :)
