### ISSUE TITLE
Can't run in RN 0.44

### ISSUE THREAD

**Issue by taipa-ibl** [tradle/react-native-crypto#14]
When i run the sample with in https://github.com/mvayngrib/rn-nodeify,
It is alway have a bug related to `crypto.pbkdf2Sync.toString`

`undefined is not an object (evaluating 'crypto.pbkdf2Sync.toString' `

![simulator screen shot may 28 2017 12 24 35 pm](https://cloud.githubusercontent.com/assets/19204597/26526314/a78c6a8a-43a0-11e7-8dbe-90912b3dd372.png)

**Comment by wswoodruff** [comment]
Hey @TaiPA I made a temporary shim just to get the app running: https://github.com/wswoodruff/react-native-pbkdf2-shim

I'm using the babel plugin `babel-plugin-rewrite-require` to replace requires for the `pbkdf2` module.

First, in your package.json add this line:
`"react-native-pbkdf2-shim": "git+https://git@github.com/wswoodruff/react-native-pbkdf2-shim.git",`

Then run `npm install --save-dev babel-plugin-rewrite-require`

Your .babelrc can look similar to this:
```
{
  "presets": ["react-native"],
  "sourceMaps": true,
  "plugins": [
    ["rewrite-require", {
      "aliases": {
        "pbkdf2": "react-native-pbkdf2-shim"
      }
    }]
  ]
}
```

Let me know if this works for you!

You will NOT be able to use pbkdf2 in any crypto. It will throw an error if you try to call either pbkdf2 or pbkdf2Sync

**Comment by petejkim** [comment]
add
`"pbkdf2-browser": "petejkim/pbkdf2-browser",` to your `package.json` and `pbkdf2: "pbkdf2-browser",` to the rewrite-require map to make pbkdf2 work.

**Comment by mvayngrib** [comment]
@TaiPA @petejkim u probably need to lock down the pbkdf2 version (locked down in react-native-crypto@2.0.2) due to this recent addition: https://github.com/crypto-browserify/pbkdf2/blob/master/index.js#L3

check your dependency tree and make sure you have pbkdf2 locked to 3.0.8
