### ISSUE TITLE
Using ReactNativify instead of rn-nodeify?

### ISSUE THREAD

**Issue by aschrijver** [tradle/react-native-crypto#16]
Using `react-native-crypto` requires `rn-nodeify`, but on that project README it describes itself as a hack and states:

> If you're looking for a saner approach, check out [ReactNativify](https://github.com/philikon/ReactNativify). I haven't tested it myself, but I think [philikon](https://github.com/philikon) will be happy to help.

So my question is: Can we use `react-native-crypto` this way as well?

ReactNativify code uses `crypto-browserify` at the moment and in `global.js` does not offer an example of shimming `getRandomValues` for use in production.
Changing the `crypto: 'crypto-browserify'` in babelrc `transformer.js` `crytpo: 'react-native-crypto'` on its own doesn't cut it.

I see `react-native-crypto` generates a bunch of [shim code](https://github.com/mvayngrib/react-native-crypto/issues/13). Maybe be some of that needs to added?

I have asked a similar question on the ReactNativify project: https://github.com/philikon/ReactNativify/issues/10

Thank you.

PS I have also posted this on stackoverflow: https://stackoverflow.com/q/45301900/8295283

**Comment by mvayngrib** [comment]
@aschrijver sorry for the slow response. Yes, `react-native-crypto` requires `rn-nodeify`. It seems like your question is more about ReactNativify. I don't know enough about ReactNativify to comment on its compatibility with `react-native-crypto`...so I'm not sure how I can help :)

**Comment by aschrijver** [comment]
no problem. i am too busy myself building a non-profit movement for people who care :)
called innercircles

encryption plays an important role..

i found that for more complex nodejs projects both methods are not feasible. instead started researching nodejs on android:

https://stackoverflow.com/questions/45459909/viable-options-for-running-nodejs-on-android-aug-2017

**Comment by mvayngrib** [comment]
@aschrijver thanks for the link, i haven't looked at this alternative!

just fyi, we're running a pretty complex crypto project with react-native. It's doable, though were hoops to jump through :) We've created and are using this [asyncstorage backend](https://github.com/tradle/react-native-async-storage-snappy) which uses Facebook's Conceal for encryption (on Android), [react-native-ecc](https://github.com/tradle/react-native-ecc) for elliptic curve signing/verifying and a bunch of other native modules on android and ios (see [here](https://github.com/tradle?utf8=%E2%9C%93&q=react-native&type=&language=)).

**Comment by aschrijver** [comment]
wow, this seems very cool. i'll not have time for some time to come, but i think @staltz of secure scuttlebot team might be interested as well.

thanks :+1: 

i'll close this issue now..

ps. in case you find a good solution it would be great if you could add answer to https://stackoverflow.com/questions/45301900/howto-patch-shim-crypto-getrandomvalues-for-react-native, so I bump into it later :)
