### ISSUE TITLE
how to verify JSON object in react native

### ISSUE THREAD

**Issue by b-asaf** [tradle/react-native-crypto#17]
Hi,
I am using RN version 0.45.1,
And I am trying to write an application in React Native which receives data in JSON format and I want to add digital signature to data in order to verify the message.
currently I am only interested in the application side, meaning - only the verification of the data.
The data, json object, is stored in Amazon S3 and I am planning to sign it with online tool for now.

how can I do this?

Thanks,

**Comment by mvayngrib** [comment]
@assafb81 sorry, this is out of scope of this project, as it has nothing to do with react native and react-native-crypto. First figure out how to do it with Node.js crypto!
