### ISSUE TITLE
Install only required rn-nodeify dependencies 

### ISSUE THREAD

**Issue by punksta** [tradle/react-native-crypto#21]
`rn-nodeify --install --hack` from readme installs all rn-nodeify modules. Is it possible to provide a list of packages, that are only required for react-native-crypto? 
For example  `rn-nodeify --install "process, react-native-randombytes" --hack`

**Comment by mvayngrib** [comment]
yep, see: https://github.com/mvayngrib/rn-nodeify#examples

but you'll need to know everything react-native-crypto pulls in, which is usually a matter of trial and error.

**Comment by punksta** [comment]
These are only required for validate rsa singing.
 `rn-nodeify --install vm,crypto,stream --hack`
Maybe for other features it will  require some extra.
