### ISSUE TITLE
Last step in react-native-crypto script breaks project

### ISSUE THREAD

**Issue by Kielan** [tradle/react-native-crypto#26]
```

# install node core shims and recursively hack package.json files
# in ./node_modules to add/update the "browser"/"react-native" field with relevant mappings
./node_modules/.bin/rn-nodeify --hack --install

```
This is a pretty hacky solution and I'm pretty sure does not work with react-native 0.56.0 but because of a lack of explanation of what is actually being done in this script combined with react native's always anonymous async bridging it's pretty tough to know what happened, how my project was changed by the script, how I could reverse it, trouble shooting, ect. I am also not the only one who has written issues pointing this out. Thank you very much for this project I'd love to do what I can to help others use it as well.

For my example use case I followed the exact instructions, no shims.js file was created, and I am left not knowing where to go from there. 
edit: Now after having written this I have found the nodeify module and am reading up on it, and will search through the issue list for related.

**Comment by mvayngrib** [comment]
@Kielan did going through the rn-nodeify docs clear things up?
