### ISSUE TITLE
superCtor is undefined

### ISSUE THREAD

**Issue by giovanischiar** [tradle/react-native-crypto#27]
I follow all steps and when I'll use I get this error.

**Comment by mvayngrib** [comment]
more info please

**Comment by giovanischiar** [comment]
Nevermind, i got some problems with rn-nodeify step. I'm using yarn but the default is npm. I ran with --yarn flag and it worked.

**Comment by mvayngrib** [comment]
@giovanischiar great! I'll close this for now then
