### ISSUE TITLE
Update the README now that React Native supports the "react-native" keyword in package.json

### ISSUE THREAD

**Issue by pcowgill** [tradle/react-native-crypto#29]
The README for this repo says, "Note: this module is a clone of crypto-browserify, with randombytes replaced. When React Native begins to support the "react-native" keyword in package.json, this module may go away".

React Native now supports the keyword in package.json, and the other `tradle` package [rn-nodeify](https://github.com/tradle/rn-nodeify) adds both to package.json.

How should we update this README based on that? Thanks!

**Comment by mvayngrib** [comment]
basically we can just delete the statement "When React Native begins to support the "react-native" keyword in package.json, this module may go away" as this package is still needed to cover a few other edge cases
