### ISSUE TITLE
Problem installing the package

### ISSUE THREAD

**Issue by johnygomez** [tradle/react-native-crypto#3]
Hi, I tried to install the package. I followed all tricks I could fould, even the "fix" from [9917779](https://github.com/mvayngrib/rn-nodeify/commit/9917779ed9a461c6c43ba410b9f0bf6372c6f31a), but running the app always fails on error 
### "undefined is not an object (evaluating 'process.version.split')"

Any ideas what to do?

**Comment by mvayngrib** [comment]
did u require the shim.js created by rn-nodeify? Require it first thing in your code

**Comment by johnygomez** [comment]
Well, no I didn't know I had to include one..this apparently solved the problem. Thanks.
Can you please add all installation steps to the Readme file(Docs)? I also had to "hack" the randombytes package and so on..it might be useful for future users.

**Comment by mvayngrib** [comment]
@johnygomez you're absolutely right. Could you take a look at the updated readme? What was the randombytes package hack you were referring to?

**Comment by johnygomez** [comment]
Sure I can. I would just append some notes..
1. I had to install package `react-native-randombytes` manually (IDK why), due to the error with RNRandomBytes.seed. Also there might be another problems with missing dependencies, which must be installed manually.
2. To make this package working i had to install hack [9917779](https://github.com/mvayngrib/rn-nodeify/commit/9917779ed9a461c6c43ba410b9f0bf6372c6f31a) to `./node_modules/rn-nodeify/`
3. After that I added RandomBytes to MainApplication.java file according to [@Timbo925 comment](https://github.com/mvayngrib/rn-nodeify/commit/9917779ed9a461c6c43ba410b9f0bf6372c6f31a)
   3a. When I followed the randombytes guide and wrote rnpm link after all this steps, I encountered a problem with building a project `Cannot evaluate module react-native-tcp : Configuration with name 'default' not found.`
   I don't know if it has something with these packages, but I unlinked it manually and everything worked just fine.

I think that's all I struggled with, but if I remember something else, I'll let you know :)

**Comment by mvayngrib** [comment]
@johnygomez thanks! I'll adjust to readme to clear this up

**Comment by johnygomez** [comment]
@mvayngrib Sure, hope it'll help future users :)

**Comment by mvayngrib** [comment]
@johnygomez updated and tested with a new project. I'll close the issue but let me know if you run into some other problems

**Comment by johnygomez** [comment]
@mvayngrib I was installing it on new computer and ran into a problem with rn-nodeify hack..I had to rewrite the file `./node-modules/rn-nodeify/pkg-hacks.js` according to [9917779](https://github.com/mvayngrib/rn-nodeify/commit/9917779ed9a461c6c43ba410b9f0bf6372c6f31a) . Maybe you could add it to the docs/possible problems section

**Comment by mvayngrib** [comment]
@johnygomez that hack is part of the recent 7.0.0 release, so if you install rn-nodeify@7, it should be included

**Comment by tedwong** [comment]
@johnygomez  can u share how u resolve this issue?
