### ISSUE TITLE
Require cycle

### ISSUE THREAD

**Issue by ilyozzz** [tradle/react-native-crypto#30]
When I run my react native app I have a warning:
`Require cycle: node_modules/react-native-crypto/index.js -> node_modules/react-native-randombytes/index.js -> node_modules/sjcl/sjcl.js -> node_modules/react-native-crypto/index.js`

My .babelrc:
```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "sourceMaps": true,
  "plugins": [
    ["babel-plugin-rewrite-require", {
      "aliases": {
        "crypto": "react-native-crypto",
        "http": "http-browserify",
        "https": "https-browserify",
        "os": "os-browserify",
        "stream": "stream-browserify",
        "vm": "vm-browserify"
      }
    }]
  ]
}
```

It looks like sjcl.js require `crypto` module which is replaced by `react-native-crypto`. Is there any methods how to avoid it?

**Comment by mvayngrib** [comment]
@arnage unfortunately i don't have any experience with `babel-plugin-rewrite-require`, I use [rn-nodeify](https://github.com/tradle/rn-nodeify) and haven't hit this issue in recent memory 

Full disclosure: I'm the author of rn-nodeify

**Comment by mvayngrib** [comment]
closing for now. If someone wants to explore compatibility with rewrite-require further, happy to re-open

**Comment by learncodingforweb** [comment]
After installing **react-native-crypto** as per steps mentioned on "**react-native": "0.62.2**"

**Getting following warning message**

[Fri May 01 2020 19:17:26.534]  WARN     Require cycle: node_modules/react-native-crypto/index.js -> node_modules/react-native-randombytes/index.js -> node_modules/sjcl/sjcl.js -> node_modules/react-native-crypto/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri May 01 2020 19:17:26.535]  WARN     Require cycle: node_modules/asn1.js/lib/asn1.js -> node_modules/asn1.js/lib/asn1/api.js -> node_modules/asn1.js/lib/asn1.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri May 01 2020 19:17:26.536]  WARN     Require cycle: node_modules/asn1.js/lib/asn1/base/index.js -> node_modules/asn1.js/lib/asn1/base/buffer.js -> node_modules/asn1.js/lib/asn1/base/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri May 01 2020 19:17:26.537]  WARN     Require cycle: node_modules/asn1.js/lib/asn1/base/index.js -> node_modules/asn1.js/lib/asn1/base/node.js -> node_modules/asn1.js/lib/asn1/base/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri May 01 2020 19:17:26.538]  WARN     Require cycle: node_modules/asn1.js/lib/asn1/base/index.js -> node_modules/asn1.js/lib/asn1/base/node.js -> node_modules/asn1.js/lib/asn1/base/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri May 01 2020 19:17:26.538]  WARN     Require cycle: node_modules/asn1.js/lib/asn1/base/index.js -> node_modules/asn1.js/lib/asn1/base/node.js -> node_modules/asn1.js/lib/asn1/base/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri May 01 2020 19:17:26.539]  WARN     Require cycle: node_modules/asn1.js/lib/asn1/constants/index.js -> node_modules/asn1.js/lib/asn1/constants/der.js -> node_modules/asn1.js/lib/asn1/constants/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri May 01 2020 19:17:26.542]  WARN     Require cycle: node_modules/asn1.js/lib/asn1.js -> node_modules/asn1.js/lib/asn1/decoders/index.js -> node_modules/asn1.js/lib/asn1/decoders/der.js -> node_modules/asn1.js/lib/asn1.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri May 01 2020 19:17:26.543]  WARN     Require cycle: node_modules/asn1.js/lib/asn1.js -> node_modules/asn1.js/lib/asn1/encoders/index.js -> node_modules/asn1.js/lib/asn1/encoders/der.js -> node_modules/asn1.js/lib/asn1.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

**Comment by Anupamchap** [comment]
@learncodingforweb have you found any solution for this issue?

**Comment by mvayngrib** [comment]
is the require cycle actually causing any problems?

**Comment by bychung** [comment]
same issue here.

**Comment by mvayngrib** [comment]
@bychung those are warnings. Has this resulted in anything breaking for you?

**Comment by bychung** [comment]
> @bychung those are warnings. Has this resulted in anything breaking for you?

Most of warnings cause problems. In my case, shows "TypeError: Cannot read property 'split' of undefined" at below stacks:
node_modules/pbkdf2/browser.js: <global>
node_modules/metro/src/lib/polyfills/require.js: loadModuleImplementation
node_modules/mero/src/lib/polyfills/require.js: guardedLoadModule
node_modules/mero/src/lib/polyfills/require.js: metroRequire
node_modules/react-native-crypto/index.js: exports.getHashes
...

**Comment by mvayngrib** [comment]
@bychung did you check what's on that line in the version of pbkdf2 u have installed `node_modules/pbkdf2/browser.js:`?

**Comment by bychung** [comment]
> @bychung did you check what's on that line in the version of pbkdf2 u have installed `node_modules/pbkdf2/browser.js:`?

I'm using Typescript v3.8.3 and didn't install pbkdf2 explicitly, but by depenency. And its version is 3.0.8.
In addtion, dived into pbkdf2, it requires 'crypto', so maybe it makes circluar requires?

**Comment by nihp** [comment]
Any solution?

**Comment by mvayngrib** [comment]
@bychung works fine for me, see an example project: https://github.com/mvayngrib/rncryptoexample

**Comment by mvayngrib** [comment]
@bychung i doubt ur problem is related to require cycles, it's more likely it's doing something like `process.version.split(...` somewhere

**Comment by bychung** [comment]
> @bychung works fine for me, see an example project: https://github.com/mvayngrib/rncryptoexample

Okay. I'll find out myself. Thank you.

**Comment by mvayngrib** [comment]
@bychung sounds good. If you find that it is an issue with this library please update us! good luck!

**Comment by suraneti** [comment]
Any updates? I got this warning but no effect on my app.

**Comment by mrosendin** [comment]
> @arnage unfortunately i don't have any experience with `babel-plugin-rewrite-require`, I use [rn-nodeify](https://github.com/tradle/rn-nodeify) and haven't hit this issue in recent memory
> 
> Full disclosure: I'm the author of rn-nodeify

I am also seeing the warning using `rn-nodify`

**Comment by ammedinap93** [comment]
> > @arnage unfortunately i don't have any experience with `babel-plugin-rewrite-require`, I use [rn-nodeify](https://github.com/tradle/rn-nodeify) and haven't hit this issue in recent memory
> > Full disclosure: I'm the author of rn-nodeify
> 
> I am also seeing the warning using `rn-nodify`

Me too.
Require cycle: node_modules\stream-browserify\index.js -> node_modules\readable-stream\readable.js -> node_modules\stream-browserify\index.js

I'm using rn-nodify and I'm facing this error. Any help will be appreciated.

Error: ENOENT: no such file or directory, open 'fileExists@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.petmimo&modulesOnly=false&runModule=true'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at getCodeFrame (D:\Archivos\Trabajo\Petmimo\probando\oci-typescript-sdk\Petmimo\node_modules\metro\src\Server.js:1296:18)
    at D:\Archivos\Trabajo\Petmimo\probando\oci-typescript-sdk\Petmimo\node_modules\metro\src\Server.js:1367:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\Archivos\Trabajo\Petmimo\probando\oci-typescript-sdk\Petmimo\node_modules\metro\src\Server.js:146:24)
    at _next (D:\Archivos\Trabajo\Petmimo\probando\oci-typescript-sdk\Petmimo\node_modules\metro\src\Server.js:168:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 ERROR  TypeError: _$$_REQUIRE(_dependencyMap[3], "fs").existsSync is not a function. (In '_$$_REQUIRE(_dependencyMap[3], "fs").existsSync(ConfigFileReader.expandUserHome(filepath))', '_$$_REQUIRE(_dependencyMap[3], "fs").existsSync' is undefined)

**Comment by AleeeKoi** [comment]
Hi @mvayngrib 
I'm getting same error
```
Require cycle: node_modules\react-native-crypto\index.js -> node_modules\react-native-randombytes\index.js -> node_modules\sjcl\sjcl.js -> node_modules\react-native-crypto\index.js
```

I have installed rn-nodify choosing only some module (cause auto installing all break the build). So, currently I have installed `crypto`, `randombytes`, `stream`, `events` and `process`.

I'm missing something required? Thank you

**Comment by helinyu** [comment]
I'm getting same error

 WARN  Require cycle: node_modules/react-native-crypto/index.js -> node_modules/react-native-randombytes/index.js -> node_modules/sjcl/sjcl.js -> node_modules/react-native-crypto/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle. 

How to fix it?

**Comment by mvayngrib** [comment]
@AleeeKoi @helinyu this require cycle shouldn't cause any problems, does it actually break anything for u?

**Comment by helinyu** [comment]
> @AleeeKoi @helinyu this require cycle shouldn't cause any problems, does it actually break anything for u?

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

**Comment by mvayngrib** [comment]
@helinyu yes, "can result" in general, but in this specific case, does it result in uninitialized values? it shouldn't

**Comment by SavelevaOnClick** [comment]
WARN  Require cycle: node_modules/react-native-crypto/index.js -> node_modules/react-native-randombytes/index.js -> node_modules/sjcl/sjcl.js -> node_modules/react-native-crypto/index.js


Does not break anything, there is no solution for cleaning the warning?

**Comment by mvayngrib** [comment]
@SavelevaOnClick can u clarify why u need to clear the warning?

**Comment by SavelevaOnClick** [comment]
> @SavelevaOnClickМожете ли вы уточнить, почему вам нужно очистить предупреждение?


in order to remove the warning from the console

**Comment by mvayngrib** [comment]
you can try using LogBox.ignoreLogs https://reactnative.dev/docs/debugging#logbox

**Comment by SavelevaOnClick** [comment]
> you can try using LogBox.ignoreLogs https://reactnative.dev/docs/debugging#logbox

that's just the point that does not hide,
tried to hide even all warnings

**Comment by mvayngrib** [comment]
sorry, not sure then 🤷

**Comment by akinncar** [comment]
@SavelevaOnClick 
```js
LogBox.ignoreLogs(['Require cycle:']);
```
https://github.com/akinncar/frogchain/blob/main/src/App.tsx#L5-L7

**Comment by teaualune** [comment]
Recently facing this warning as well, and I figured out a dirty fix (via patch-package) to solve this issue. However, since I'm very unfamiliar with crypto stuffs, I didn't test everything properly so it might actually break things (not happened on me for now). Please use with care 😵‍💫 

The strange part of this fix is that it patches both `react-native-randombytes` and `sjcl` packages instead of touching `react-native-crypto`. I believe there's a more clever way to do this.

---

`react-native-randombytes+3.6.1.patch`

```
diff --git a/node_modules/react-native-randombytes/index.js b/node_modules/react-native-randombytes/index.js
index 7478cb3..fcee560 100644
--- a/node_modules/react-native-randombytes/index.js
+++ b/node_modules/react-native-randombytes/index.js
@@ -15,6 +15,11 @@ function init () {
   if (RNRandomBytes.seed) {
     let seedBuffer = toBuffer(RNRandomBytes.seed)
     addEntropy(seedBuffer)
+
+    // migrated from sjcl/core/random.js
+    let buf = randomBytes(1024/8);
+    buf = new Uint32Array(new Uint8Array(buf).buffer);
+    addEntropy(buf, 1024, 'crypto.randomBytes');
   } else {
     seedSJCL()
   }

```

---

`sjcl+1.0.8.patch`

```
diff --git a/node_modules/sjcl/core/random.js b/node_modules/sjcl/core/random.js
index 77c5951..78c7d9d 100644
--- a/node_modules/sjcl/core/random.js
+++ b/node_modules/sjcl/core/random.js
@@ -481,12 +481,7 @@ sjcl.random = new sjcl.prng(6);
 (function(){
   // function for getting nodejs crypto module. catches and ignores errors.
   function getCryptoModule() {
-    try {
-      return require('crypto');
-    }
-    catch (e) {
-      return null;
-    }
+    return null;
   }
 
   try {
diff --git a/node_modules/sjcl/sjcl.js b/node_modules/sjcl/sjcl.js
index c3c3ea9..4b481a0 100644
--- a/node_modules/sjcl/sjcl.js
+++ b/node_modules/sjcl/sjcl.js
@@ -47,7 +47,7 @@ this.a.mouseCollector),document.detachEvent("keypress",this.a.keyboardCollector)
 a.touches[0]||a.changedTouches[0];this.addEntropy([a.pageX||a.clientX,a.pageY||a.clientY],1,"touch");C(this,0)},ma:function(){C(this,2)},ea:function(a){a=a.accelerationIncludingGravity.x||a.accelerationIncludingGravity.y||a.accelerationIncludingGravity.z;if(window.orientation){var b=window.orientation;"number"===typeof b&&this.addEntropy(b,1,"accelerometer")}a&&this.addEntropy(a,2,"accelerometer");C(this,0)}};
 function A(a,b){var c,d=sjcl.random.K[a],e=[];for(c in d)d.hasOwnProperty(c)&&e.push(d[c]);for(c=0;c<e.length;c++)e[c](b)}function C(a,b){"undefined"!==typeof window&&window.performance&&"function"===typeof window.performance.now?a.addEntropy(window.performance.now(),b,"loadtime"):a.addEntropy((new Date).valueOf(),b,"loadtime")}function y(a){a.b=z(a).concat(z(a));a.L=new sjcl.cipher.aes(a.b)}function z(a){for(var b=0;4>b&&(a.h[b]=a.h[b]+1|0,!a.h[b]);b++);return a.L.encrypt(a.h)}
 function B(a,b){return function(){b.apply(a,arguments)}}sjcl.random=new sjcl.prng(6);
-a:try{var D,E,F,G;if(G="undefined"!==typeof module&&module.exports){var H;try{H=require("crypto")}catch(a){H=null}G=E=H}if(G&&E.randomBytes)D=E.randomBytes(128),D=new Uint32Array((new Uint8Array(D)).buffer),sjcl.random.addEntropy(D,1024,"crypto['randomBytes']");else if("undefined"!==typeof window&&"undefined"!==typeof Uint32Array){F=new Uint32Array(32);if(window.crypto&&window.crypto.getRandomValues)window.crypto.getRandomValues(F);else if(window.msCrypto&&window.msCrypto.getRandomValues)window.msCrypto.getRandomValues(F);
+a:try{var D,E,F,G;if(G="undefined"!==typeof module&&module.exports){var H=null;G=E=H}if(G&&E.randomBytes)D=E.randomBytes(128),D=new Uint32Array((new Uint8Array(D)).buffer),sjcl.random.addEntropy(D,1024,"crypto['randomBytes']");else if("undefined"!==typeof window&&"undefined"!==typeof Uint32Array){F=new Uint32Array(32);if(window.crypto&&window.crypto.getRandomValues)window.crypto.getRandomValues(F);else if(window.msCrypto&&window.msCrypto.getRandomValues)window.msCrypto.getRandomValues(F);
 else break a;sjcl.random.addEntropy(F,1024,"crypto['getRandomValues']")}}catch(a){"undefined"!==typeof window&&window.console&&(console.log("There was an error collecting entropy from the browser:"),console.log(a))}
 sjcl.json={defaults:{v:1,iter:1E4,ks:128,ts:64,mode:"ccm",adata:"",cipher:"aes"},ja:function(a,b,c,d){c=c||{};d=d||{};var e=sjcl.json,f=e.g({iv:sjcl.random.randomWords(4,0)},e.defaults),g;e.g(f,c);c=f.adata;"string"===typeof f.salt&&(f.salt=sjcl.codec.base64.toBits(f.salt));"string"===typeof f.iv&&(f.iv=sjcl.codec.base64.toBits(f.iv));if(!sjcl.mode[f.mode]||!sjcl.cipher[f.cipher]||"string"===typeof a&&100>=f.iter||64!==f.ts&&96!==f.ts&&128!==f.ts||128!==f.ks&&192!==f.ks&&0x100!==f.ks||2>f.iv.length||
 4<f.iv.length)throw new sjcl.exception.invalid("json encrypt: invalid parameters");"string"===typeof a?(g=sjcl.misc.cachedPbkdf2(a,f),a=g.key.slice(0,f.ks/32),f.salt=g.salt):sjcl.ecc&&a instanceof sjcl.ecc.elGamal.publicKey&&(g=a.kem(),f.kemtag=g.tag,a=g.key.slice(0,f.ks/32));"string"===typeof b&&(b=sjcl.codec.utf8String.toBits(b));"string"===typeof c&&(f.adata=c=sjcl.codec.utf8String.toBits(c));g=new sjcl.cipher[f.cipher](a);e.g(d,f);d.key=a;f.ct="ccm"===f.mode&&sjcl.arrayBuffer&&sjcl.arrayBuffer.ccm&&

```

---

So, how this fix works is that it moves an `addEntropy` call from `sjcl` into `react-native-randombytes`.

In `sjcl`, we mocked `getCryptoModule` so the `addEntropy` part in `sjcl/core/random.js` will not be called (since I'm only dealing with mobile RN, the `window` part is ignored). Since it is skipped, I pasted it manually into `react-native-randombytes` package.

By mocking `getCryptoModule`, the require cycle will be broken at `sjcl`, thus resolving the warning.

**Comment by mvayngrib** [comment]
you guys should use a combination of [react-native-get-random-values](https://www.npmjs.com/package/react-native-get-random-values) to polyfill crypto.getRandomValues + [randombytes](https://github.com/crypto-browserify/randombytes) (browser fallback) instead. react-native-randombytes should be deprecated
