### ISSUE TITLE
Please update with randomFillSync

### ISSUE THREAD

**Issue by qalqi** [tradle/react-native-crypto#31]
randomFillSync is undefined 
Here is crypto-browserify with randomFillSync
https://github.com/crypto-browserify/crypto-browserify/blob/460a13b5bf1e4ea60dc995906ba0543f7933a32b/index.js#L71

**Comment by qalqi** [comment]
#32  Pull request created

Anybody with same error can use  

`npm i github:qalqi/react-native-crypto`

**Comment by mvayngrib** [comment]
closed by #32
