### ISSUE TITLE
Not understand doc

### ISSUE THREAD

**Issue by callmejm** [tradle/react-native-crypto#33]
Sorry I can't really understand
```
# install node core shims and recursively hack package.json files
# in ./node_modules to add/update the "browser"/"react-native" field with relevant mappings
./node_modules/.bin/rn-nodeify --hack --install
```

after `npm i --save-dev tradle/rn-nodeify` i stuck

**Comment by mvayngrib** [comment]
that comment just explains what running `./node_modules/.bin/rn-nodeify --hack --install` does. Did you run that command?

**Comment by mvayngrib** [comment]
closing, will re-open if someone still needs clarity here
