### ISSUE TITLE
JavaCompile error

### ISSUE THREAD

**Issue by techkrtk** [tradle/react-native-crypto#34]
react-native-version: 0.60.5
java: 8

react-native run-android doesn't build by throwing the following error

**> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot C:\Users\karth\Desktop\Nvest\gxwallet-cli\node_modules\react-native\android

> Task :react-native-os:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
48 actionable tasks: 8 executed, 40 up-to-date
C:\Users\karth\Desktop\Nvest\gxwallet-cli\node_modules\react-native-os\android\src\main\java\com\peel\react\RNOSModule.java:31: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error

FAILURE: Build failed with an exception.**

**Comment by mvayngrib** [comment]
@techkrtk your error comes from react-native-os, not react-native-crypto

**Comment by techkrtk** [comment]
but i think that is dependency installed while I installed rn-nodify, because I havent installed react-native-os myself, that is why I raised issued here @mvayngrib

**Comment by techkrtk** [comment]
@mvayngrib  Is the react-native-crypto is updated for support in react-native 0.60.x version?

**Comment by mvayngrib** [comment]
@techkrtk rn-nodeify doesn't require you to install react-native-os, you can whitelist the modules you want pulled in. You should open an issue on react-native-os though!

> Is the react-native-crypto is updated for support in react-native 0.60.x version?

i'm not aware of anything that needs to be updated

**Comment by techkrtk** [comment]
okay thanks @mvayngrib

**Comment by AleeeKoi** [comment]
Hi @techkrtk did you have resolved? I'm stuck with same error.. 
Thank you

**Comment by techkrtk** [comment]
Nope.
