### ISSUE TITLE
Missing method: `scryptSync`

### ISSUE THREAD

**Issue by danilowoz** [tradle/react-native-crypto#35]
Isn't this method implement? Or is there an equivalent method? 

Thanks for supporting the package 🥇

**Comment by mvayngrib** [comment]
@danilowoz you might be able to use https://github.com/cryptocoinjs/scryptsy

they support `scryptSync` but i think the process of making it a node.js shim got stalled (https://github.com/cryptocoinjs/scryptsy/pull/12) so it depends on whether u want to use it directly (probably can), or transparently via `require('crypto').scryptSync` (can't yet)

**Comment by danilowoz** [comment]
Thanks for your answer.
I would like to use in transparently way, so any plans to implementing it?
Might I open a PR to update the roadmap

**Comment by mvayngrib** [comment]
@danilowoz feel free to open a PR to update the roadmap :) I might not have much time in the near future to work on this, but i'll try to make time to review PRs
