### ISSUE TITLE
item.copy is not a function

### ISSUE THREAD

**Issue by kevinvn1709** [tradle/react-native-crypto#5]
Thanks for great lib, @mvayngrib
I am using publicEncrypt/privateDecrypt (rsa). But I got this error.

![image](https://cloud.githubusercontent.com/assets/1281425/19505884/be3a1722-95f0-11e6-9eaa-c16cc225cb55.png)

Please review my case!

**Comment by mvayngrib** [comment]
@kevinvn1709 it's hard to say without seeing the code, but a possible reason is Buffer.concat receiving a TypedArray not a Buffer instance

**Comment by kevinvn1709** [comment]
Thanks @mvayngrib. You are right. It is my mistake, I had changed some code and now it works perfectly.

**Comment by mvayngrib** [comment]
@kevinvn1709 great! i'll close this then
