### ISSUE TITLE
Question: run rn-nodeify --install with mandatory package only 

### ISSUE THREAD

**Issue by johanschram** [tradle/react-native-crypto#55]
Hi ! 

A quick question, 
When doing rn-nodeify --install --hack, I suspect it installs much more packages than actually needed to for react-native-crypto. I Might be wrong thought... Anyway, if this is the case, has someone the list of the mandatory packages to make all features of react-native-crypto work ? 

Thanks !

**Comment by mvayngrib** [comment]
@johanschram not sure, but off the top of my head, this might do it

```
rn-nodeify --install process,stream,inherits,crypto,events,assert,os,string_decoder,util,constants,buffer --hack
```

haha, added a bunch more after looking at the list

**Comment by johanschram** [comment]
Thanks ! 

Actually I will go for this [option](https://github.com/tradle/react-native-crypto/issues/46) which feel a little bit cleaner :)

**Comment by johanschram** [comment]
> --install process,stream,inherits,crypto,events,assert,os,string_decoder,util,constants,buffer --hack

Apparently vm is needed too.
