### ISSUE TITLE
typerror null is not an object RNRandombytes.seed - iOS

### ISSUE THREAD

**Issue by shridhar48** [tradle/react-native-crypto#56]
Integrated react-native-crypto to a react-native project.
Project is working fine in Android but for iOS getting the below error
"typerror null is not an object RNRandombytes.seed"

package.json
`
 "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "rn-nodeify --install crypto,process,stream,events --hack"
  },
 "dependencies": {,
    "crypto-js": "3.1.9-1",
    "events": "^1.0.0",
    "process": "^0.11.0",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-crypto": "^2.2.0",
    "react-native-randombytes": "^3.5.3",]
    "readable-stream": "1.0.33",
    "stream-browserify": "^1.0.0",
    "vm-browserify": "0.0.4"
},
 "devDependencies": {
    "@babel/core": "7.9.6",
    "@babel/runtime": "7.9.6",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.58.0",
    "react-test-renderer": "16.11.0",
    "rn-nodeify": "^10.2.0"
  },
`

**Comment by samsouci** [comment]
Hey, I'm running into the same problem as you were. Could you explain how did you solve it ? Many thanks!

**Comment by minhthuhai** [comment]
Delete Podfile.lock
cd ios && pod install --repo-update && cd ..
