### ISSUE TITLE
Problem with ECDH keypair generation

### ISSUE THREAD

**Issue by johnygomez** [tradle/react-native-crypto#7]
Hi, I recently encountered a problem with ECDH initialization.
I used the following code:

```
const ecdh = crypto.createECDH('secp521r1');
const publicKey = ecdh.generateKeys();
```

however it produces an error
> Error: Not implemented yet

I traced the error back to the 'elliptic' lib that uses 'brorand' lib for rand numbers, which contains some old code that throws this error...

I want to ask, whether anybody tried this functionality, and if so, was it working properly?

Thanks.

**Comment by mvayngrib** [comment]
@johnygomez  try the latest https://github.com/mvayngrib/rn-nodeify

i added the getRandomValues shim to shim.js

**Comment by johnygomez** [comment]
@mvayngrib I'm sorry but it's not working.
I think that problem is not in function getRandomValues but in function [_rand()](https://github.com/indutny/brorand/blob/master/index.js#L37) in **brorand** package..
More specifically, **Elliptic** package calls it [here](https://github.com/indutny/elliptic/blob/master/lib/elliptic/ec/index.js#L60) with invalid argument I think..
Can you test the functionality of ECDH please?

**Comment by mvayngrib** [comment]
@johnygomez seems to work fine here (index.common.js has your two line ecdh example): https://github.com/mvayngrib/rnctest

**Comment by johnygomez** [comment]
@mvayngrib Sorry, I forgot, that I have to copy the shim.js to the root folder after the update.
Now it seems to be working at my app too..
Thanks for now :)

**Comment by mvayngrib** [comment]
@johnygomez ah yea, i fell for that a few times. Glad you got it working :)
