### ISSUE TITLE
Failed to match tag: "int" at: ["modulus"]

### ISSUE THREAD

**Issue by kevinvn1709** [tradle/react-native-crypto#8]
Hi, @mvayngrib 
There is an tricky bug with publicEncrypt function.

I deep into the source code to debug at ~/node_modules/asn1.js/lib/asn1/decoders/der.js file. I got error at line

![image](https://cloud.githubusercontent.com/assets/1281425/20144261/a2861c3a-a6ce-11e6-89e8-31ecba722c5d.png)

And error throw out the screen like this
![image](https://cloud.githubusercontent.com/assets/1281425/20144276/ad7f4ee0-a6ce-11e6-9d89-792545420a93.png)

But, when I comment this block code (by pass that check). My code will work as a charm. I did not know about that validate for? Could you explain for me about that?

**Comment by mvayngrib** [comment]
@kevinvn1709 sorry, don't know much about the internals of the various libs assembled in react-native-crypto. At the moment I'm very busy, but I'll have a look in a few days. I hope you figure it out by then!

**Comment by kevinvn1709** [comment]
Thanks for your quick response.
I found that this error comes from XCode 8.1. Maybe It is not suitable with latest version of XCode

I had cloned your repo RNCTest (https://github.com/mvayngrib/rnctest) and run with XCode 8.1. It produces same errors. So I spend time to downgrade to Xcode 7.3.1 then it works again.

**Comment by mvayngrib** [comment]
@kevinvn1709 actually i ran into something yesterday that might be related to this. Because iOS 10 has an updated JavaScriptCore, there are some bugs when using a dependency of [Buffer](https://github.com/feross/buffer) < 4.5. So if you're using XCode 8 and testing on iOS 10, make sure that if you have buffer among the dependencies, it's >= 4.5. I updated react-native-randombytes and react-native-ecc yesterday because of this issue. Let me know if that helps!

**Comment by kevinvn1709** [comment]
@mvayngrib: Its so great. I rebuild my source code with your updates. It works perfectly on Xcode 8.1 and iOS 10.
Thanks for your works.

**Comment by mvayngrib** [comment]
@kevinvn1709 so glad to hear that! Good luck with your project

**Comment by cbartondock** [comment]
Having the same issue (thank you so much for doing the hard work of finding the cause kevinvn1709), but my crypto libraries are up to date. I'm hesitant to hackily disable a check in the asn1 file... will check which buffer versions I am depending on.

**Comment by mvayngrib** [comment]
closing for now due to inactivity
